#!/usr/bin/env python
# quid - quick Latin to English search of Whitaker's words

import sys, requests, bs4

BASE_URL = 'http://archives.nd.edu/cgi-bin/wordz.pl?keyword='

if len(sys.argv) < 2:
    print('Usage: quid [Latin search term]')
    sys.exit()

term = sys.argv[1]
url = BASE_URL + term

r = requests.get(url)
html = bs4.BeautifulSoup(r.text, "html.parser")
lat = html.select('pre')[0].getText()

print(lat)
