#!/usr/bin/env python
# whit - quick English to Latin search of Whitaker's words

import sys, requests, bs4

BASE_URL = 'http://archives.nd.edu/cgi-bin/wordz.pl?english='

if len(sys.argv) < 2:
    print('Usage: whit [English search term]')
    sys.exit()

term = sys.argv[1]
url = BASE_URL + term

r = requests.get(url)
html = bs4.BeautifulSoup(r.text, "html.parser")
eng = html.select('pre')[0].getText()

print(eng)
